FROM python:3-alpine

WORKDIR /build
RUN pip install pipenv
COPY Pipfile* /build/
RUN pipenv install --system --deploy \
 && rm -rf /build

WORKDIR /app
COPY web/main.py web.py

EXPOSE 8080/tcp
CMD python web.py
